import {
  pgTable,
  uuid,
  text,
  boolean,
  integer,
  timestamp,
  unique,
} from 'drizzle-orm/pg-core';

// ─── owners ──────────────────────────────────────────────────────────────────
// id comes from Supabase Auth – it is never auto-generated by the database.
export const owners = pgTable('owners', {
  id:         uuid('id').primaryKey(),
  username:   text('username').unique().notNull(),
  email:      text('email').unique().notNull(),
  created_at: timestamp('created_at').defaultNow(),
});

export type Owner       = typeof owners.$inferSelect;
export type NewOwner    = typeof owners.$inferInsert;

// ─── workers ─────────────────────────────────────────────────────────────────
export const workers = pgTable('workers', {
  id:         uuid('id').primaryKey().defaultRandom(),
  owner_id:   uuid('owner_id')
                .notNull()
                .references(() => owners.id, { onDelete: 'cascade' }),
  name:       text('name').notNull(),
  created_at: timestamp('created_at').defaultNow(),
});

export type Worker      = typeof workers.$inferSelect;
export type NewWorker   = typeof workers.$inferInsert;

// ─── containers ──────────────────────────────────────────────────────────────
// slug is stored as "{username}/{game_code}" (no leading slash)
export const containers = pgTable(
  'containers',
  {
    id:         uuid('id').primaryKey().defaultRandom(),
    owner_id:   uuid('owner_id')
                  .notNull()
                  .references(() => owners.id, { onDelete: 'cascade' }),
    game_name:  text('game_name').notNull(),
    game_code:  text('game_code').notNull(),
    slug:       text('slug').unique().notNull(),
    is_active:  boolean('is_active').default(true),
    created_at: timestamp('created_at').defaultNow(),
  },
  (table) => [
    unique('containers_owner_id_game_code_unique').on(table.owner_id, table.game_code),
  ],
);

export type Container     = typeof containers.$inferSelect;
export type NewContainer  = typeof containers.$inferInsert;

// ─── orders ──────────────────────────────────────────────────────────────────
// status values: QUEUE | PROGRESS | DONE | ARCHIVED
export const orders = pgTable(
  'orders',
  {
    id:            uuid('id').primaryKey().defaultRandom(),
    container_id:  uuid('container_id')
                     .notNull()
                     .references(() => containers.id, { onDelete: 'cascade' }),
    worker_id:     uuid('worker_id')
                     .references(() => workers.id, { onDelete: 'set null' }),
    queue_number:  integer('queue_number').notNull(),
    customer_name: text('customer_name').notNull(),
    details:       text('details'),
    status:        text('status').default('QUEUE'),
    created_at:    timestamp('created_at').defaultNow(),
    updated_at:    timestamp('updated_at').defaultNow(),
  },
  (table) => [
    unique('orders_container_id_queue_number_unique').on(table.container_id, table.queue_number),
  ],
);

export type Order     = typeof orders.$inferSelect;
export type NewOrder  = typeof orders.$inferInsert;

// ─── registration_attempts ───────────────────────────────────────────────────
export const registrationAttempts = pgTable('registration_attempts', {
  id:           uuid('id').primaryKey().defaultRandom(),
  ip_address:   text('ip_address').notNull(),
  attempted_at: timestamp('attempted_at').defaultNow(),
});

export type RegistrationAttempt     = typeof registrationAttempts.$inferSelect;
export type NewRegistrationAttempt  = typeof registrationAttempts.$inferInsert;
